config/routes.rb
Rails.application.routes.draw do

  resources :search_suggestions
  resources :searches
  resources :activities
  resources :learns
  resources :answers
  resources :questions
  resources :categories do
    resources :lessons
  end
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :learns

  accepts_nested_attributes_for :learns, :allow_destroy => true

  scope :get_lesson_belongsto_user, -> user_id {where user_id: user_id}
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.where(category_id: params[:category_id],
                            user_id: current_user.id)
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @result = @lesson.learns
  end

  # GET /lessons/new
  def new
    category = Category.find(params[:category_id])
    learned_ids = Learn.learned_ids(current_user,category)
    if learned_ids.empty?
      flash[:danger] = "We has some error. Sory about that"
      redirect_to request.referer
    else
      questions = category.questions.question_not_learn(learned_ids).take(5)
      @lesson = category.lessons.build
      questions.each do |question|
        @lesson.learns.build question_id: question.id
      end
    end
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = current_user.lessons.build(category_id: params[:category_id])
    learns = params[:lesson][:learns_attributes]
    if @lesson.save
      learns.each do |key, value|
        @lesson.learns.create(answer_id: value["answer_id"],
                              question_id: value["question_id"],
                              is_correct: Learn.correct?(value["answer_id"]))
        end
        score = @lesson.learns.where(is_correct: true).count
        @lesson.update(score: score)
        Activity.create!(user_id: current_user.id, action: 3, source: @lesson.id)
        redirect_to category_lesson_path(@lesson.category, @lesson), 
        notice: 'Lesson was successfully created.'
      else
        render :new
      end
    end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:category_id, :score, :user_id, learns_attributes: [:question_id, :answer_id])
    end
  end

app/helpers/lessons_helper.rb
module LessonsHelper
  def get_answers(id)
    answers = []
    Question.find(id).answers.each do |answer|
      answers << answer
    end
    answers.shuffle
  end

  def get_question(id)
    Question.find(id).content
  end

  def your_answer(id)
    if id.nil?
      return ""
    else
      Answer.find(id).content
    end
  end

  def correct_answer(id)
    Answer.find_by(question_id: id, is_correct: true).content
  end

  def get_learned(category_id)
    lesson_ids = current_user.lessons.where(category_id: category_id)
    @learned_ids = [0]
    lesson_ids.each do |lesson|
      lesson.learns.where(is_correct: true).each do |learn|
        @learned_ids << learn.question_id
      end
    end
  end
end

app/views/lessons/_form.html.erb
<%= form_for(lesson) do |f| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <h1>Your Lesson</h1>
      <div class="box-body">
        <table class="table table-hover">
          <tr>
            <th>#</th>
            <th>Lesson</th>
            <th>Score</th>
            <th></th>
          </tr>
          <% i=0 %>
          <% @lessons.each do |lesson| %>
            <tr>
              <td><%= i=i+1 %></td>
              <td>Lesson <%= i %></td>
              <td><%= lesson.score %> / <%= lesson.learns.count %></td>
              <td><%= link_to 'Show', category_lesson_path(lesson.category_id, lesson), class: "btn btn-primary" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="processBox">
      <h1 class="timer-container" id="#run-the-timer">
        <span class="minute">00</span>:<span class="second">10</span>
        <span class="timeout_message_show" style="display:none;">We are Sorry, your time is up !</span>
      </h1>
    </div>
  </div>

  <div class="col-sm-8">
    <% i=0 %>
    <%= form_for @lesson, url: {:action => "create"} do |l| %>
        <%= l.fields_for :learns do |f| %>
            <div class="panel panel-primary" id="basepanel1">
              <div class="panel-heading">
                Question <%= i=i+1 %>
              </div>
              <div class="panel-body">
                <p><strong><%= get_question(f.object.question_id)%></strong></p>
                <%= f.collection_radio_buttons(:answer_id, get_answers(f.object.question_id), :id, :content, include_hidden: false) do |b|%>
                  <div class="radio">
                    <%= b.label { b.radio_button + b.text } %>
                  </div>
                <% end %>
                <%= f.hidden_field :question_id %>
              </div>
            </div>
      <% end %>
      <%= l.submit %>
    <% end %>
  </div>
  <div class="col-md-2">
    <div class="processBox">
      <h3> Your progress </h3>
      <h3>
        <span id="answer_count">0</span>/<%= i%>
      </h3>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    var fragmentTime;
    $('.timeout_message_show').hide();
    var minutes = jQuery('span.minute').text();
    var seconds = jQuery('span.second').text();
    minutes = parseInt(minutes);
    seconds = parseInt(seconds);
    if (isNaN(minutes)) {
      minutes = 00;
    }
    if (isNaN(seconds)) {
      seconds = 00;
    }
    if (minutes == 60) {
      minutes = 59;
    }
    if (seconds == 60) {
      seconds = 59;
    }
    fragmentTime = (60 * minutes) + (seconds);
    displayMinute = document.querySelector('span.minute');
    displaySecond = document.querySelector('span.second');
    startTimer(fragmentTime, displayMinute, displaySecond);
  });
</script>

app/views/lessons/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <h1>Result: <%= @lesson.score %></h1>
      <div class="box-body">
        <table class="table table-hover">
          <tr>
            <th>#</th>
            <th>Question</th>
            <th>Your Answer</th>
            <th>Correct Answer</th>
            <th>Correct</th>
          </tr>
          <% i=0 %>
          <% @result.each do |learn| %>
            <tr>
              <td><%= i=i+1 %></td>
              <td><%= get_question(learn.question_id) %></td>
              <td><%= your_answer(learn.answer_id) %></td>
              <td><%= correct_answer(learn.question_id) %></td>
              <td><span class="success glyphicon glyphicon-ok"></span></td>
            </tr>
          <% end %>
        </table>
        <div class="text-center">
          <%= link_to "Categories", categories_path, class: "btn btn-primary" %>
          <%= link_to "New Lesson", new_category_lesson_path(@lesson.category_id),
                class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>