config/routes.rb
Rails.application.routes.draw do

  resources :search_suggestions
  resources :searches
  resources :activities
  resources :learns
  resources :answers
  resources :questions
  resources :categories do
    resources :lessons
  end
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
  has_many :lessons
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @questions = @category.questions
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :picture)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def quantity_of_question(category)
    Category.find(category.id).questions.count
  end

  def your_result(category)
    lessons = category.lessons.get_lesson_belongsto_user(current_user.id)
    result = 0
    if lessons.nil?
      return result
    else
      lessons.each do |lesson|
        result = result + lesson.learns.is_correct?.count
      end
    end
    return result
  end

  def is_finished?(category_id)
    quantity_of_question(category_id) == your_result(category_id) ? true : false
  end
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <% @categories.each do |category|%>
      <div class="col-md-4">
        <div class="product-item">
          <div class="pi-img-wrapper">
            <img src="<%= category.picture %>" class="img-responsive" 
                 alt="Berry Lace Dress">
            <div>
              <%= link_to "Word", category_path(category), class: "btn" %>
              <%= link_to "History", category_lessons_path(category), 
                                     class: "btn" %>
            </div>
          </div>
          <h3><%= category.name %></h3>
          <div class="pi-price">
            <%= your_result(category) %>/<%= quantity_of_question(category) %>
          </div>
          <% if is_finished?(category) %>
            <a class="btn add2cart disabled">Finish</a>
          <% else %>
            <%= link_to "New Lesson", new_category_lesson_path(category),                        
                                      class: "btn add2cart" %>
          <% end %>
          <div class="sticker sticker-new"></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @category.picture %>
</p>

<table>
  <tr>
    <th>#</th>
    <th>Word</th>
    <th>Mean</th>
    <th>Status</th>
  </tr>
  <% i=0 %>
  <% @questions.each do |question| %>
    <tr>
      <th><%= i=i+1 %></th>
      <th><%= question.content %></th>
      <th><%= correct_answer(question.id) %></th>
      <% if learned?(question.id, question.category_id) %>
        <th>Yes</th>
      <% else %>
        <th>No</th>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>